//
//  Brewfile.swift
//  Brewui
//
//  Created by Michael McKay on 1/11/26.
//

import Foundation

/// Represents a Homebrew Brewfile for package list export/import
/// Format follows the standard `brew bundle` Brewfile format
struct Brewfile: Codable, Sendable {
    
    /// List of taps (third-party repositories)
    var taps: [String] = []
    
    /// List of formulas (CLI packages)
    var formulas: [FormulaEntry] = []
    
    /// List of casks (GUI applications)
    var casks: [CaskEntry] = []
    
    /// Metadata about the Brewfile
    var metadata: Metadata?
    
    struct FormulaEntry: Codable, Sendable, Hashable, Identifiable {
        nonisolated var id: String { name }
        let name: String
        var options: [String]?
        var restart_service: Bool?
        var link: Bool?
        var conflicts_with: [String]?
        
        nonisolated init(name: String, options: [String]? = nil) {
            self.name = name
            self.options = options
        }
    }
    
    struct CaskEntry: Codable, Sendable, Hashable, Identifiable {
        nonisolated var id: String { name }
        let name: String
        var args: [String: String]?
        
        nonisolated init(name: String, args: [String: String]? = nil) {
            self.name = name
            self.args = args
        }
    }
    
    struct Metadata: Codable, Sendable {
        var createdAt: Date
        var createdBy: String?
        var description: String?
        var macOSVersion: String?
        var homebrewVersion: String?
        
        nonisolated init(
            createdAt: Date = Date(),
            createdBy: String? = nil,
            description: String? = nil,
            macOSVersion: String? = nil,
            homebrewVersion: String? = nil
        ) {
            self.createdAt = createdAt
            self.createdBy = createdBy
            self.description = description
            self.macOSVersion = macOSVersion
            self.homebrewVersion = homebrewVersion
        }
    }
    
    nonisolated init(
        taps: [String] = [],
        formulas: [FormulaEntry] = [],
        casks: [CaskEntry] = [],
        metadata: Metadata? = nil
    ) {
        self.taps = taps
        self.formulas = formulas
        self.casks = casks
        self.metadata = metadata
    }
    
    /// Total number of packages
    nonisolated var totalCount: Int {
        formulas.count + casks.count
    }
    
    /// Creates a Brewfile from a list of BrewPackages
    nonisolated init(from packages: [BrewPackage], metadata: Metadata? = nil) {
        self.taps = []
        self.formulas = packages
            .filter { $0.type == .formula }
            .map { FormulaEntry(name: $0.fullName) }
            .sorted { $0.name.lowercased() < $1.name.lowercased() }
        
        self.casks = packages
            .filter { $0.type == .cask }
            .map { CaskEntry(name: $0.name) }
            .sorted { $0.name.lowercased() < $1.name.lowercased() }
        
        self.metadata = metadata
    }
    
    /// Generates Brewfile content in standard format
    nonisolated func generateContent(includeComments: Bool = true) -> String {
        var lines: [String] = []
        
        // Header comment with metadata
        if includeComments, let metadata = metadata {
            lines.append("# Brewfile generated by Brewui")
            lines.append("# Created: \(ISO8601DateFormatter().string(from: metadata.createdAt))")
            if let desc = metadata.description {
                lines.append("# Description: \(desc)")
            }
            if let macOS = metadata.macOSVersion {
                lines.append("# macOS: \(macOS)")
            }
            lines.append("")
        }
        
        // Taps
        if !taps.isEmpty {
            if includeComments {
                lines.append("# Third-party repositories")
            }
            for tap in taps.sorted() {
                lines.append("tap \"\(tap)\"")
            }
            lines.append("")
        }
        
        // Formulas
        if !formulas.isEmpty {
            if includeComments {
                lines.append("# Command-line tools (formulas)")
            }
            for formula in formulas {
                var line = "brew \"\(formula.name)\""
                if let options = formula.options, !options.isEmpty {
                    line += ", args: [\(options.map { "\"\($0)\"" }.joined(separator: ", "))]"
                }
                if let restart = formula.restart_service, restart {
                    line += ", restart_service: true"
                }
                lines.append(line)
            }
            lines.append("")
        }
        
        // Casks
        if !casks.isEmpty {
            if includeComments {
                lines.append("# GUI Applications (casks)")
            }
            for cask in casks {
                var line = "cask \"\(cask.name)\""
                if let args = cask.args, !args.isEmpty {
                    let argsString = args.map { "\($0.key): \"\($0.value)\"" }.joined(separator: ", ")
                    line += ", \(argsString)"
                }
                lines.append(line)
            }
        }
        
        return lines.joined(separator: "\n")
    }
    
    /// Parses Brewfile content into a Brewfile struct
    nonisolated static func parse(content: String) throws -> Brewfile {
        var taps: [String] = []
        var formulas: [FormulaEntry] = []
        var casks: [CaskEntry] = []
        
        let lines = content.components(separatedBy: .newlines)
        
        for line in lines {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            
            // Skip empty lines and comments
            if trimmed.isEmpty || trimmed.hasPrefix("#") {
                continue
            }
            
            // Parse tap
            if trimmed.hasPrefix("tap ") {
                if let name = extractQuotedString(from: trimmed, prefix: "tap") {
                    taps.append(name)
                }
                continue
            }
            
            // Parse brew (formula)
            if trimmed.hasPrefix("brew ") {
                if let name = extractQuotedString(from: trimmed, prefix: "brew") {
                    formulas.append(FormulaEntry(name: name))
                }
                continue
            }
            
            // Parse cask
            if trimmed.hasPrefix("cask ") {
                if let name = extractQuotedString(from: trimmed, prefix: "cask") {
                    casks.append(CaskEntry(name: name))
                }
                continue
            }
        }
        
        return Brewfile(taps: taps, formulas: formulas, casks: casks)
    }
    
    /// Extracts the first quoted string after a prefix
    private nonisolated static func extractQuotedString(from line: String, prefix: String) -> String? {
        let pattern = #"^\s*\#(prefix)\s*"([^"]+)""#.replacingOccurrences(of: "#(prefix)", with: prefix)
        
        guard let regex = try? NSRegularExpression(pattern: pattern),
              let match = regex.firstMatch(
                in: line,
                range: NSRange(line.startIndex..., in: line)
              ),
              let range = Range(match.range(at: 1), in: line) else {
            return nil
        }
        
        return String(line[range])
    }
}

// MARK: - File Extensions

extension Brewfile {
    /// Standard file extension for Brewfiles
    static let fileExtension = "brewfile"
    
    /// All supported file extensions
    static let supportedExtensions = ["brewfile", "Brewfile", "txt", ""]
    
    /// UTI for Brewfiles
    static let contentType = "public.plain-text"
}
